<?php

namespace P4M\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostArchiveRepository extends EntityRepository
{
}
