<?php

namespace P4M\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;
use P4M\UserBundle\Entity\User;
/**
 * PostViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostViewRepository extends EntityRepository
{
    
    public function findViewedPostsId(User $user)
    {
//        $em = $this->getEntityManager();
//        $qb = $em->createQueryBuilder();
//        $qb->select('count(p.id)');
//        $qb ->from('P4MCoreBundle:Post','p')
//        
//        $qb = $catrep ->createQueryBuilder('cc')
//                            ->select('DISTINCT cc.contenttype')
//                            ->Where('cc.contenttype = :type')
//                            ->setParameter('type', 'blogarticle')
//                            ->getQuery();
//
//        $categories = $category->getResult();
//        
//        
//        $qb = $this ->createQueryBuilder('pv')
//                    ->select('DISTINCT pv.post')
//                    ->;
//        
//        $qb->where($qb)
        
        
    }
    
    public function findLastMonthPostReadNumberByUser($user)
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(DISTINCT p.post)');
        $qb->from('P4MTrackingBundle:PostView','p');
        $qb ->where('p.user = :user')
            ->setParameter('user', $user)
            ->andWhere('p.datein>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );

        
        
        return $qb->getQuery()->getSingleScalarResult();
        
        
    }
    public function findLastMonthPostReadNumber()
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(DISTINCT p.id)');
        $qb->from('P4MTrackingBundle:PostView','p');
        $qb ->where('p.datein>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );

        
        return $qb->getQuery()->getSingleScalarResult();
        
        
    }
    public function findLastMonthPostRead()
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $qb = $this->createQueryBuilder('pv');
        $qb ->where('pv.datein>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );

        
        return $qb->getQuery()->getResult();
        
        
}
}

