<?php

namespace P4M\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WallViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallViewRepository extends EntityRepository
{
    
    public function findLastView($user, $wall)
    {
        $qb = $this->createQueryBuilder('v')
                    ->where('v.wall = :wallId')
                    ->setParameter('wallId', $wall->getId())
                    ->andWhere('v.user = :userId' )
                    ->setParameter('userId',$user->getId())
                    
                    ->orderBy('v.date','DESC')
                    ->setFirstResult(0)
                    ->setMaxResults(1);
        
        return $qb->getQuery()->getResult();
    }
}
