parameters:
#    p4_m_moderation.example.class: P4M\ModerationBundle\Example

services:
#    p4_m_moderation.example:
#        class: %p4_m_moderation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
