parameters:
#    skcms_core.example.class: SKCMS\CoreBundle\Example

services:
#    skcms_core.example:
#        class: %skcms_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
