<?php

namespace P4M\MangoPayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MangoUserNaturalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangoUserNaturalRepository extends EntityRepository
{
}
