_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    
    

p4m_core_defaultStrews:
    path: /userToAuthor
    defaults: { _controller: P4MCoreBundle:Import:fromUserToAuthor}
#p4m_core_defaultStrews:
#    path: /defaultStrews
#    defaults: { _controller: P4MCoreBundle:Import:defaultStrews}
#p4m_core_flag:
#    path: /setFlags
#    defaults: { _controller: P4MCoreBundle:Import:setFlags}
#p4m_core_scores:
#    path: /setScore
#    defaults: { _controller: P4MCoreBundle:Import:setScore}
#p4m_core_roles:
#    path: /setRoles/{userName}/{role}
#    defaults: { _controller: P4MCoreBundle:Import:setRoles}

#p4m_core_deletePosts:
#    path: /deletePosts
#    defaults: { _controller: P4MCoreBundle:Import:deletePosts }

#p4m_core_importLangues:
#    path: /importLangues
#    defaults: { _controller: P4MCoreBundle:Import:insertLangues }
#p4m_core_aupdateActivities:
#    path: /updateActivity
#    defaults: { _controller: P4MCoreBundle:Import:updateActivity }
#p4m_core_importCountry:
#    path: /importCountries
#    defaults: { _controller: P4MCoreBundle:Import:insertCountry }

#p4m_core_assignTags:
#    path: /assignTags
#    defaults: { _controller: P4MCoreBundle:Import:assignTags}

#p4m_core_slug:
#    path: /forceSlugs
#    defaults: { _controller: P4MCoreBundle:Import:postSlug }
#
#p4m_core_resetslug:
#    path: /resetSlugs
#    defaults: { _controller: P4MCoreBundle:Import:resetSlug }
#p4m_core_oldPosts:
#    path: /import
#    defaults: { _controller: P4MCoreBundle:Import:import }
#    
#p4m_core_oldUsers:
#    path: /import_users
#    defaults: { _controller: P4MCoreBundle:Import:importUsers }
    