p4_mapi:
    resource: "@P4MAPIBundle/Resources/config/routing.yml"
    prefix:   /

skcms_locale:
    resource: "@SKCMSLocaleBundle/Resources/config/routing-translations.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_console:
    resource: "@P4MConsoleBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_my_elastica:
    resource: "@P4MMyElasticaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_blog:
    resource: "@P4MBlogBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_mango_pay:
    resource: "@P4MMangoPayBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_contact:
    resource: "@P4MContactBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/contact
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

#p4_m_mail:
#    resource: "@P4MMailBundle/Resources/config/routing.yml"
#    prefix:   /
#
p4_m_admin:
    resource: "@P4MAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin-old
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

skcms_admin:
    resource: "@SKCMSAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

skcms_admin:
    resource: "@SKCMSAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_notification:
    resource: "@P4MNotificationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_pinocchio:
    resource: "@P4MPinocchioBundle/Resources/config/routing.yml"
    prefix:   /

p4_m_backoffice:
    resource: "@P4MBackofficeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/my-account
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_tracking:
    resource: "@P4MTrackingBundle/Resources/config/routing.yml"
    prefix:   /

p4_m_moderation:
    resource: "@P4MModerationBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /{_locale}/secure_area/connect
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /{_locale}/secure_area/connect
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /{_locale}/secure_area/connect
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

hwi_facebook_login:
    path: /secure_area/login/check-facebook

p4_m_admin:
    resource: "@P4MAdminBundle/Resources/config/routing.yml"
    prefix:   /admin-old

p4_m_user:
    resource: "@P4MUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

p4_m_core:
    resource: "@P4MCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/secure_area
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/secure_area/profile
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/secure_area/register
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/secure_area/resetting
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/secure_area/profile
    requirements:
      _locale: en|fr
    defaults:
      _locale: %locale%

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

p4_m_api:
    resource: "@P4MAPIBundle/Resources/config/routing.yml"
    prefix:   /api