security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        P4M\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_AUTEUR:      [ROLE_USER]
        ROLE_MODERATEUR : [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_AUTEUR, ROLE_MODERATEUR]       # Un admin hérite des droits d'auteur et de modérateur
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email
        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/secure_area/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main_reset:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/secure_area/resetting
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        register:
            pattern:   ^/secure_area/register
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
#        home:
#            pattern:   ^/$
#            anonymous: true
#            provider:  fos_userbundle
#        home:
#            pattern:   ^/$
#            anonymous: false
#            provider: fos_userbundle
#            form_login:
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
#            logout:
#                path:       fos_user_security_logout
#                target:     /
#        console:
#            pattern:   ^/console
#            anonymous: true
#            provider:  fos_userbundle
       
        

        secure_area:
            pattern: ^[/]*

            oauth:
                failure_path: hwi_oauth_connect
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                resource_owners:
                    facebook:           "/secure_area/login/check-facebook"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: p4m_core_wall #default location to redirect after successful login
                #success_handler: P4M_core.locale_listener_onauth

            anonymous: ~
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login #where to go after logout

#        main:
#            pattern:   ^[/]*
#            anonymous: true
#            provider: fos_userbundle
#            form_login:
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
#            logout:
#                path:       fos_user_security_logout
#                target:     /
            

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin-old, roles: ROLE_ADMIN }
        - { path: ^/moderation, roles: ROLE_MODERATEUR }
        - { path: ^/$, roles: [ROLE_USER,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/view/, roles: [ROLE_USER,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/strew/, roles: [ROLE_USER,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/search/, roles: [ROLE_USER,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/user/, roles: [ROLE_USER,IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/ajax, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/trendy, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/console$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area, roles: ROLE_USER }
        - { path: ^/my-account, roles: ROLE_USER }
        
#        - { path: ^/*, roles: ROLE_USER }

        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
