<?php

namespace P4M\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReadPostLaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadPostLaterRepository extends EntityRepository
{
}
