<?php

namespace P4M\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMessageRepository extends EntityRepository
{
}
