P4M_api:
    type: rest
    resource: P4M\APIBundle\Controller\DefaultController
P4M_api_list:
    type: rest
    resource: P4M\APIBundle\Controller\ListController
P4M_api_post:
    type: rest
    resource: P4M\APIBundle\Controller\PostController
P4M_api_mango:
    type: rest
    resource: @P4MAPIBundle/Controller/MangoController.php
