parameters:
#    p4_mapi.example.class: P4M\APIBundle\Example

services:
  p4m_core.header_listener:
      class:      P4M\APIBundle\Listener\HeaderListener
      tags:
         - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
