parameters:
#    p4_mapi.example.class: P4M\APIBundle\Example

services:
  api.header_listener:
      class:      P4M\APIBundle\Listener\HeaderListener
      tags:
         - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  api.listupdate_suscriber:
      class: P4M\APIBundle\Listener\ListUpdaterSuscriber
      calls:
          -  [ setContainer, [@service_container] ]
      tags:
          - { name: doctrine.event_subscriber, connection: default }
