<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use P4M\UserBundle\Entity\User;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function findViewedCategories(User $user)
    {
        $qb = $this->createQueryBuilder('c')
                    ->leftJoin('c.posts', 'p')
                    ->innerJoin('p.views','vi','WITH','vi.user = :user')
//                    ->where('vi.user = :user')
                    ->setParameter('user', $user)
                    ->distinct()
                    ->orderBy('c.name');
        
        return $qb->getQuery()->getResult();
        
        
    }
    
    public function findReadLaterCategories(User $user)
    {
        $qb = $this->createQueryBuilder('c')
                    ->join('c.posts', 'p')
                    ->innerjoin('p.readLater','rl','WITH','rl.user = :user')
//                    ->where('rl.user = :user')
                    ->setParameter('user', $user)
                    ->distinct()
                    ->orderBy('c.name');
        
        return $qb->getQuery()->getResult();
        
        
    }
}
