<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangRepository extends EntityRepository
{
    
    public function findByWalls($user)
    {
        $qb = $this->createQueryBuilder('l');
        
        $qb ->leftJoin('\P4M\CoreBundle\Entity\Wall','w')
            ->where('w.user=:user')
            ->setParameter('user',$user);
    }
}
