<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PressformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressformRepository extends EntityRepository
{
    public function findByRecipient($user)
    {
        $qb = $this->createQueryBuilder('p');
    
        $qb->innerJoin('p.post', 'pp','WITH','pp.author=:user')
            ->setParameter('user', $user);
        
        $qb->orderBy('p.date', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    
    public function findLastMonthNumberByUser($user)
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(p.id)');
        $qb->from('P4MCoreBundle:PressForm','p');
        $qb ->where('p.sender = :user')
            ->setParameter('user', $user)
            ->andWhere('p.date>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );
        
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function findLastMonthNumber()
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(p.id)');
        $qb->from('P4MCoreBundle:PressForm','p');
        $qb ->where('p.date>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );
        
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function findLastMonthPressformersNumber()
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('count(DISTINCT p.sender)');
        $qb->from('P4MCoreBundle:PressForm','p');
        $qb ->where('p.date>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );
        
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function findLastMonthPressedContentNumber()
    {
        $lastMonth = new \DateTime();
        $lastMonth->modify('-1 month');
        
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb ->select('count(DISTINCT p.post)');
        $qb ->from('P4MCoreBundle:PressForm','p');
        
        $qb ->where('p.date>:lastMonth')
            ->setParameter('lastMonth', $lastMonth );
        
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}
