<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findPaginated($page=1,$nombreParPage = 350)
    {
        $qb = $this->createQueryBuilder('t')
                ->addSelect('COUNT(p.id) as HIDDEN nPosts')
                ->join('t.posts', 'p')
                ->groupBy('t.id')
                ->orderBy("nPosts", 'DESC')
                ->setFirstResult(($page-1)*$nombreParPage)
                ->setMaxResults($nombreParPage);
        
        return $qb->getQuery()->getResult();
    }
}
