<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrustedSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrustedSourceRepository extends EntityRepository
{
}
