<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnpressformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnpressformRepository extends EntityRepository
{
}
