<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use P4M\UserBundle\Entity\User;

/**
 * WallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallRepository extends EntityRepository
{
    
    public function findByUserActions(User $user,$limit=15,$offset=0)
    {
        $qb = $this ->createQueryBuilder('w')
                    ->leftJoin('w.comments', 'co')
                    ->leftJoin('w.votes', 'v');
        
//        $qb = $this->addScore($qb);
        
        $qb ->where('w.user=:user')
            ->orWhere('co.user=:user')
            ->orWhere('v.user=:user')
//            ->where('v.score=:score')
//            ->setParameter('score', "1")
            ->setParameter('user', $user->getId());
                
        $qb ->orderBy('w.dateUpdate','DESC')
            ->addOrderBy('co.dateUpdated', 'DESC')
            ->addOrderBy('v.date', 'DESC')
//            ->setFirstResult( $offset)
//            ->setMaxResults($limit)
            ;
        
        return $qb->getQuery()->getResult();
            
            
    }
    
    public function findByUserCustom(User $user,$limit=15,$offset=0,$postData = array())
    {
        $qb = $this ->createQueryBuilder('w');
        $qb ->where('w.user=:user')
            ->setParameter('user', $user);
        
        $qb ->orderBy('w.dateUpdate','DESC')
            ;
        
        return $qb->getQuery()->getResult();
    }
}
