<?php

namespace P4M\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnpressformTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WantPressformRepository extends EntityRepository
{
    public function findAllGroupped()
    {
        $qb = $this->createQueryBuilder('w');
        $qb ->groupBy('w.post')
            ->addSelect('GROUP_CONCAT(w.twitter) twitters')
            ->addSelect('GROUP_CONCAT(w.email) emails')
//            ->addSelect('GROUP_CONCAT(w.post)')
            ->addSelect('COUNT(w.id) total')
            ->leftJoin('w.post','post')
            ->addSelect('post')
            
                ;
        
        return $qb->getQuery()->getResult();
    }
    public function findAllByPost(Post $post)
    {
        $qb = $this->createQueryBuilder('w');
        $qb ->where('w.post = :post')
            ->setParameter('post', $post)
            
                ;
        
        return $qb->getQuery()->getResult();
    }
    
}
