sk_admin_homepage:
    path:  /
    defaults: { _controller: SKCMSAdminBundle:Admin:index }
sk_admin_list:
    path:  /list/{entity}/{page}
    defaults: { _controller: SKCMSAdminBundle:List:index, page:1 }
sk_admin_edit:
    path:  /edit/{entity}/{id}
    defaults: { _controller: SKCMSAdminBundle:Edit:index, id:null }
sk_admin_delete:
    path:  /delete/{entity}/{id}
    defaults: { _controller: SKCMSAdminBundle:Edit:delete}
sk_admin_charge_wallet:
    path:  /wallet/charge
    defaults: { _controller: SKCMSAdminBundle:Wallet:list}
sk_admin_wallet_charge_user:
    path:  /wallet/charge/user/{id}
    defaults: { _controller: SKCMSAdminBundle:Wallet:charge}
sk_admin_wanted_pressforms:
    path:  /authors/wanted-pressforms
    defaults: { _controller: SKCMSAdminBundle:Author:wantedPressformList}
sk_admin_temp_author:
    path:  /authors/temp-author/{postSlug}
    defaults: { _controller: SKCMSAdminBundle:Author:tempAuthor}
sk_admin_user_list:
    path:  /users/list
    defaults: { _controller: SKCMSAdminBundle:User:userList}
#sk_admin_press:
#    path:  /users/list
#    defaults: { _controller: SKCMSAdminBundle:User:userList}
#sk_admin_user_list:
#    path:  /users/list
#    defaults: { _controller: SKCMSAdminBundle:User:userList}
