<?php

namespace P4M\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    
    
    public function findUnreadNumber($user)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->select('count(n.id)');
        $qb ->where('n.user=:user')
            ->setParameter('user',$user)
            ->andWhere('n.read=:viewed')
            ->setParameter('viewed', 0);
        
        return $qb->getQuery()->getSingleScalarResult();
                
    }
    
    public function findByUserPaginated($user,$page=1,$nombreParPage = 10)
    {
        $qb = $this->createQueryBuilder('n');
        $qb ->where('n.user=:user')
            ->setParameter('user',$user)
            ->setFirstResult($nombreParPage * ($page -1) )
            ->setMaxResults($nombreParPage)
            ->orderBy('n.date','DESC')
            ;
        
        return $qb->getQuery()->getResult();
    }
}
