parameters:
    #    p4_m_tracking.example.class: P4M\TrackingBundle\Example

services:
#    p4_m_tracking.example:
#        class: %p4_m_tracking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
