<?php

namespace P4M\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WPBlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WPBlogPostRepository extends EntityRepository
{
    
    public function findAllPaginated($page=1,$nombreParPage=30)
    {
        $qb = $this->createQueryBuilder('w');
        
        $qb->getFirstResult(($page-1)*$nombreParPage);
        $qb->setMaxResults($nombreParPage);
        $qb->orderBy('w.date','desc');
        
        return $qb->getQuery()->getResult();
        
    }
}
