<?php

namespace P4M\PinocchioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostScoreRepository extends EntityRepository
{
    
    public function findBestScore()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s.score')
           ->orderBy('s.score','DESC')
           ->setFirstResult(0)
           ->setMaxResults(1);
        
        return $qb->getQuery()->getSingleScalarResult();
    }
}
