#p4_m_mango_pay_homepage:
#    pattern:  /register-card-return/{cardId}
#    defaults: { _controller: P4MMangoPayBundle:Card:register }

p4_m_mango_pay_register_card:
    pattern:  /register-card
    defaults: { _controller: P4MMangoPayBundle:Card:register }

p4_m_mango_pay_register_card_return:
    pattern:  /register-card-return/{cardId}/{ammount}/{preAuthorisation}
    defaults: { _controller: P4MMangoPayBundle:Card:registerReturn }

p4_m_mango_pay_wallet_charge:
    pattern:  /wallet-charge/{cardId}/{ammount}/{preAuthorisation}
    defaults: { _controller: P4MMangoPayBundle:Wallet:charge }

p4_m_mango_pay_wallet_charge_post:
    pattern:  /wallet-charge
    defaults: { _controller: P4MMangoPayBundle:Wallet:chargePost }
