parameters:
#    p4_m_mango_pay.example.class: P4M\MangoPayBundle\Example

services:
    p4_m_mango_pay.api:
        class: P4M\MangoPayBundle\MangoPaySDK\MangoPayApi
    p4_m_mango_pay.util:
        class: P4M\MangoPayBundle\MangoPaySDK\MangoPay
        arguments: [ @doctrine.orm.entity_manager, @p4_m_mango_pay.api,%mango_client_id%,%mango_client_pass% ]
#    p4_m_mango_pay.example:
#        class: %p4_m_mango_pay.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
