p4_m_backoffice_homepage:
    path:  /
    defaults: { _controller: P4MBackofficeBundle:BackOffice:index }

p4_m_backoffice_profile_infos:
    path:  /profile-infos
    defaults: { _controller: P4MBackofficeBundle:Profile:myAccount }

p4_m_backoffice_password:
    path:  /profile-password
    defaults: { _controller: P4MBackofficeBundle:Profile:myAccountPassword }

p4_m_backoffice_profile_picture:
    path:  /profile-picture
    defaults: { _controller: P4MBackofficeBundle:Profile:pictureEdit }

p4_m_backoffice_notifications:
    path:  /notifications
    defaults: { _controller: P4MBackofficeBundle:Notification:notification }
    
#WALLS
p4m_backoffice_wall_create:
    path:  /strew-create
    defaults: { _controller: P4MCoreBundle:Wall:create}
    
p4m_backoffice_wall_edit:
    path:  /strew-edit/{wallSlug}
    defaults: { _controller: P4MCoreBundle:Wall:create}
    requirements:
        wallSlug: ([\w@. -]+[/]?([a-zA-Z@-]+[0-9]*))

p4_m_backoffice_walls:
    path:  /walls
    defaults: { _controller: P4MBackofficeBundle:Wall:wallEdit }

p4_m_backoffice_wallAdd:
    path:  /wall-add
    defaults: { _controller: P4MBackofficeBundle:Wall:wallEdit }

p4_m_backoffice_wallEdit:
    path:  /wall-edit/{wallSlug}
    defaults: { _controller: P4MBackofficeBundle:Wall:wallEdit }
    requirements:
        wallSlug: ([\w@. -]+[/]?([a-zA-Z@-]+[0-9]*))

   
#PRODUCER
p4_m_backoffice_producer_key:
    path:  /producer/key
    defaults: { _controller: P4MBackofficeBundle:Producer:key }
p4_m_backoffice_producer_money:
    path:  /producer/payouts
    defaults: { _controller: P4MBackofficeBundle:Producer:payOuts }
p4_m_backoffice_producer_pressforms:
    path:  /producer/pressforms
    defaults: { _controller: P4MBackofficeBundle:Producer:pressforms }
    
p4_m_backoffice_producer_activate:
    path:  /producer/activate
    defaults: { _controller: P4MBackofficeBundle:Producer:activate }
p4_m_backoffice_producer_bankAccount:
    path:  /producer/bank-account
    defaults: { _controller: P4MBackofficeBundle:Money:accounts }
    
#MANGO PAY
p4_m_backoffice_money:
    path:  /money
    defaults: { _controller: P4MBackofficeBundle:Money:index }
    


p4_m_backoffice_money_bankAccount_create_iban:
    path:  /money/bank-account/create/iban
    defaults: { _controller: P4MBackofficeBundle:Money:accountCreateIban }
#
#p4_m_backoffice_dashboardReader:
#    path:  /dashboardReader
#    defaults: { _controller: P4MBackofficeBundle:BackOffice:dashboardReader }
#    
#
#p4_m_backoffice_profileEdit:
#    path:  /profile
#    defaults: { _controller: P4MBackofficeBundle:Profile:profileEdit }
#    
