parameters:
#    p4_m_backoffice.example.class: P4M\BackofficeBundle\Example

services:
#    p4_m_backoffice.example:
#        class: %p4_m_backoffice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
