<?php

namespace P4M\ModerationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WallFlagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallFlagRepository extends EntityRepository
{
}
