<?php

namespace P4M\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPublicStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPublicStatusRepository extends EntityRepository
{
}
