<?php

namespace P4M\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use P4M\UserBundle\Entity\User;
/**
 * UserLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLinkRepository extends EntityRepository
{
    
    
    public function findUserCommunity($user)
    {
        $qb = $this->createQueryBuilder('ul');
        
        $qb ->leftJoin('ul.follower','follower')
            ->leftJoin('ul.following','following')
            ->where('ul.follower=:user')
            ->orWhere('ul.following=:user')
            ->setParameter('user',$user);
        
        return $qb->getQuery()->getResult();
        
    }
}
